/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Robot.gltf 
Author: Annelida (https://sketchfab.com/Annelida)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toy-robot-domowik-8f1f61ca0c844b978abfb43243513377
Title: Toy robot Domowik
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Robot.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="a7cc487df9bc45b4836e9db71eb1e6fffbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Basement" position={[0, -14.488, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Main">
                    <group name="Object_7">
                      <group name="Armature" position={[0, 0.835, 1.185]} rotation={[-1.092, 0, 0]}>
                        <group name="Object_29">
                          <primitive object={nodes._rootJoint_1} />
                        </group>
                      </group>
                      <group name="Armature001" position={[0, -0.835, 1.185]} rotation={[1.092, 0, Math.PI]}>
                        <group name="Object_36">
                          <primitive object={nodes._rootJoint_2} />
                        </group>
                      </group>
                      <primitive object={nodes._rootJoint} />
                    </group>
                  </group>
                  <mesh name="Basement_Material_0" geometry={nodes.Basement_Material_0.geometry} material={materials.Material} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Robot.gltf')
